tasks:
  - init: sudo pip3 install ansible docker
# Ports to expose on workspace startup
ports:
  - port: 6080
    onOpen: open-preview
checkoutLocation: "/workspace/ansible_collections/community/proxysql